deploy_dev:
  script:
    - pwd
    - rsync -a ./ --exclude '.git' root@5.45.120.191:/var/www/html/tft
    - ssh -i ~/.ssh/id_rsa root@5.45.120.191 -t "/root/scripts/deploy-tft.bash"
  only:
    - dev
  allow_failure: true

deploy_prod_distributors_dashboard:
  script:
    - pwd
    # - call npm production
    - rsync -a ./dist --exclude '.git' root@207.154.221.32:/var/www/html/tft
  only:
    - master
  allow_failure: true